# Generated by Django 5.2.9 on 2026-01-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='계정코드')),
                ('category_large', models.CharField(max_length=50, verbose_name='대분류(관)')),
                ('category_medium', models.CharField(max_length=50, verbose_name='중분류(항)')),
                ('category_small', models.CharField(max_length=50, verbose_name='소분류(목)')),
                ('account_type', models.CharField(choices=[('ASSET', '자산'), ('LIABILITY', '부채'), ('INCOME', '수입'), ('EXPENSE', '비용')], max_length=10, verbose_name='계정성격')),
                ('report_position', models.CharField(blank=True, max_length=50, verbose_name='결산서 위치')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '계정과목',
                'verbose_name_plural': '계정과목',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자산명')),
                ('acquisition_date', models.DateField(verbose_name='취득일')),
                ('acquisition_cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='취득가액')),
                ('useful_life', models.IntegerField(verbose_name='내용연수')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT', '정액법'), ('DECLINING', '정률법')], default='STRAIGHT', max_length=10, verbose_name='상각방법')),
                ('salvage_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='잔존가치')),
                ('current_value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='현재잔액')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '고정자산',
                'verbose_name_plural': '고정자산',
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명')),
                ('business_number', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('partner_type', models.CharField(choices=[('MEMBER', '회원사'), ('GENERAL', '일반')], default='GENERAL', max_length=10, verbose_name='유형')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '거래처/회원사',
                'verbose_name_plural': '거래처/회원사',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(unique=True, verbose_name='회계연도')),
                ('closing_date', models.DateField(verbose_name='결산일')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출됨'), ('APPROVED', '승인됨')], default='DRAFT', max_length=10, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '결산',
                'verbose_name_plural': '결산',
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='일자')),
                ('transaction_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출'), ('TRANSFER', '대체')], max_length=10, verbose_name='구분')),
                ('description', models.CharField(max_length=200, verbose_name='적요')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='금액')),
                ('payment_method', models.CharField(choices=[('CASH', '현금'), ('BANK', '예금'), ('CARD', '법인카드'), ('OTHER', '기타')], default='BANK', max_length=10, verbose_name='결제수단')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='증빙파일')),
                ('status', models.CharField(choices=[('APPROVED', '승인'), ('PENDING', '대기')], default='APPROVED', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='계정과목')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.member', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='회계연도')),
                ('annual_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간예산액')),
                ('supplementary_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='추경예산액')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='계정과목')),
            ],
            options={
                'verbose_name': '예산',
                'verbose_name_plural': '예산',
                'ordering': ['fiscal_year', 'account__code'],
                'unique_together': {('fiscal_year', 'account')},
            },
        ),
    ]
