# Generated by Django 5.2.9 on 2026-01-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['fiscal_year', 'code'], 'verbose_name': '계정과목', 'verbose_name_plural': '계정과목'},
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='', max_length=100, verbose_name='계정명'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_name2',
            field=models.CharField(blank=True, max_length=100, verbose_name='계정명2'),
        ),
        migrations.AddField(
            model_name='account',
            name='fiscal_year',
            field=models.IntegerField(default=2026, verbose_name='회계연도'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', '자산'), ('LIABILITY', '부채'), ('INCOME', '수입'), ('EXPENSE', '비용')], default='EXPENSE', max_length=10, verbose_name='계정성격'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10, verbose_name='계정코드'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('fiscal_year', 'code')},
        ),
    ]
