# Generated by Django 5.2.9 on 2026-01-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_fiscal_year_to_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '거래내역추가', 'verbose_name_plural': '거래내역추가'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', '자산'), ('LIABILITY', '부채'), ('EQUITY', '자본'), ('INCOME', '수입'), ('EXPENSE', '비용')], default='EXPENSE', max_length=10, verbose_name='계정성격'),
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('BANK', '예금출납장'), ('CASH', '현금출납장')], max_length=10, verbose_name='출납장유형')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('entry_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10, verbose_name='구분')),
                ('date', models.DateField(verbose_name='일자')),
                ('description', models.CharField(max_length=200, verbose_name='내용')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='금액')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '출납장',
                'verbose_name_plural': '출납장',
                'ordering': ['book_type', 'year', 'month', 'entry_type', 'order'],
                'unique_together': {('book_type', 'year', 'month', 'entry_type', 'order')},
            },
        ),
    ]
