# Generated by Django 5.2.9 on 2026-01-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_cashbook_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(blank=True, max_length=50, verbose_name='예금주')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '예금계좌',
                'verbose_name_plural': '예금계좌',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cashbook',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount', verbose_name='계좌'),
        ),
        migrations.CreateModel(
            name='CashBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('BANK', '예금출납장'), ('CASH', '현금출납장')], max_length=10, verbose_name='출납장유형')),
                ('name', models.CharField(max_length=50, verbose_name='과목명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '출납장과목',
                'verbose_name_plural': '출납장과목',
                'ordering': ['book_type', 'order'],
                'unique_together': {('book_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cashbook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashbookcategory', verbose_name='과목'),
        ),
    ]
