# Generated by Django 5.2.9 on 2026-01-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_cashbook_category_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='계정과목'),
        ),
    ]
