# Generated by Django 5.2.9 on 2026-01-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_account_to_cashbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='finance.transaction', verbose_name='연결된 거래'),
        ),
    ]
