# Generated by Django 5.2.9 on 2026-01-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_linked_transaction_to_cashbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name2',
        ),
    ]
