# Generated by Django 5.2.9 on 2026-01-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_account_name2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookcategory',
            options={'ordering': ['book_type', 'entry_type', 'order'], 'verbose_name': '출납장과목', 'verbose_name_plural': '출납장과목'},
        ),
        migrations.AlterUniqueTogether(
            name='cashbookcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashbookcategory',
            name='entry_type',
            field=models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], default='INCOME', max_length=10, verbose_name='구분'),
        ),
        migrations.AlterUniqueTogether(
            name='cashbookcategory',
            unique_together={('book_type', 'entry_type', 'name')},
        ),
    ]
