# Generated by Django 5.2.9 on 2026-01-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_entry_type_to_cashbookcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookcategory',
            options={'ordering': ['book_type', 'entry_type', 'name'], 'verbose_name': '출납장과목', 'verbose_name_plural': '출납장과목'},
        ),
        migrations.RemoveField(
            model_name='cashbookcategory',
            name='order',
        ),
    ]
