# Generated by Django 5.2.9 on 2026-01-16 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_allow_blank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='book_type',
            field=models.CharField(choices=[('BANK', '예금출납장'), ('CASH', '현금출납장'), ('DEPOSIT', '예수금출납장')], max_length=10, verbose_name='출납장유형'),
        ),
        migrations.AlterField(
            model_name='cashbookcategory',
            name='book_type',
            field=models.CharField(choices=[('BANK', '예금출납장'), ('CASH', '현금출납장'), ('DEPOSIT', '예수금출납장')], max_length=10, verbose_name='출납장유형'),
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('BUDGET', '예산집행'), ('CASHBOOK_BANK', '예금출납장'), ('CASHBOOK_CASH', '현금출납장'), ('CASHBOOK_DEPOSIT', '예수금출납장')], max_length=20, verbose_name='스냅샷유형')),
                ('fiscal_year', models.IntegerField(verbose_name='회계연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('monthly_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='월 집행액')),
                ('income_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수입 합계')),
                ('expense_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='지출 합계')),
                ('prev_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='전월이월')),
                ('next_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='차월이월')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확정여부')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확정일시')),
                ('confirmed_by', models.CharField(blank=True, max_length=50, verbose_name='확정자')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='계정과목')),
            ],
            options={
                'verbose_name': '월별스냅샷',
                'verbose_name_plural': '월별스냅샷',
                'ordering': ['fiscal_year', 'month', 'snapshot_type'],
            },
        ),
    ]
