# Generated by Django 5.2.9 on 2026-01-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_monthly_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysnapshot',
            name='account_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='계정코드'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='계정명'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='annual_budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간예산'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='category_large',
            field=models.CharField(blank=True, max_length=50, verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='category_medium',
            field=models.CharField(blank=True, max_length=50, verbose_name='중분류'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='cumulative_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='누계'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='exec_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='집행률'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='잔여예산'),
        ),
    ]
