# Generated by Django 5.2.9 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_add_budget_snapshot_fields'),
    ]

    operations = [
        # 기존 개별 필드들 삭제
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='account',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='category_large',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='category_medium',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='annual_budget',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='monthly_amount',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='cumulative_amount',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='exec_rate',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='income_total',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='expense_total',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='prev_balance',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshot',
            name='next_balance',
        ),
        # snapshot_data JSONField 추가
        migrations.AddField(
            model_name='monthlysnapshot',
            name='snapshot_data',
            field=models.JSONField(default=dict, verbose_name='스냅샷데이터'),
        ),
        # unique_together 제약조건 추가
        migrations.AlterUniqueTogether(
            name='monthlysnapshot',
            unique_together={('snapshot_type', 'fiscal_year', 'month')},
        ),
    ]
