# Generated by Django 5.2.9 on 2026-01-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_simplify_monthly_snapshot_to_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '거래내역조회/삭제', 'verbose_name_plural': '거래내역조회/삭제'},
        ),
        migrations.CreateModel(
            name='DepositLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('date', models.DateField(verbose_name='일자')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='내용')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='금액')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashbookcategory', verbose_name='과목')),
            ],
            options={
                'verbose_name': '예수금출납장',
                'verbose_name_plural': '예수금출납장',
                'ordering': ['year', 'month', 'order'],
            },
        ),
    ]
