# Generated by Django 5.2.9 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_add_deposit_ledger_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='승인번호'),
        ),
    ]
