# Generated by Django 5.2.9 on 2026-01-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_approval_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbook',
            options={'ordering': ['book_type', 'year', 'month', 'entry_type', 'order'], 'verbose_name': '1. 지출/수입 기록 및 보고서 작성', 'verbose_name_plural': '1. 지출/수입 기록 및 보고서 작성'},
        ),
        migrations.AlterModelOptions(
            name='cashbookcategory',
            options={'ordering': ['fiscal_year', 'book_type', 'entry_type', 'name'], 'verbose_name': '출납장과목등록및내역조회', 'verbose_name_plural': '출납장과목등록및내역조회'},
        ),
        migrations.AlterUniqueTogether(
            name='cashbookcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashbookcategory',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='회계연도'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', '자산'), ('LIABILITY', '부채'), ('EQUITY', '자본'), ('INCOME', '수입'), ('EXPENSE', '지출')], default='EXPENSE', max_length=10, verbose_name='계정성격'),
        ),
        migrations.AlterField(
            model_name='monthlysnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('BUDGET', '예산집행'), ('CASHBOOK_BANK', '예금출납장'), ('CASHBOOK_CASH', '현금출납장'), ('CASHBOOK_DEPOSIT', '예수금출납장'), ('CARD_EXPENSE', '카드사용내역')], max_length=20, verbose_name='스냅샷유형'),
        ),
        migrations.AlterUniqueTogether(
            name='cashbookcategory',
            unique_together={('fiscal_year', 'book_type', 'entry_type', 'name')},
        ),
    ]
