"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0u#n8smvr+)c1m$v4bi*5812n3v12r+vjizm-@@g+c=2(2ee+o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Jazzmin (must be before django.contrib.admin)
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Local apps
    'common',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password validation (테스트용 비활성화)
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 인증 설정
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = 'login'

# Jazzmin 설정
JAZZMIN_SETTINGS = {
    "site_title": "VAN협회 재무관리",
    "site_header": "VAN협회",
    "site_brand": "VAN협회 재무관리",
    "welcome_sign": "VAN협회 예산/결산 관리 시스템",
    "copyright": "VAN협회",
    "search_model": ["finance.Account", "finance.Member"],
    "topmenu_links": [
        {"name": "홈", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "finance.Account": "fas fa-book",
        "finance.Member": "fas fa-building",
        "finance.Budget": "fas fa-coins",
        "finance.Transaction": "fas fa-plus-circle",
        "finance.Settlement": "fas fa-file-invoice-dollar",
        "finance.FixedAsset": "fas fa-warehouse",
        "finance.CashBook": "fas fa-file-alt",
        "finance.CashBookCategory": "fas fa-list",
    },
    "custom_links": {
        "finance": [
            {
                "name": "예금/현금출납장",
                "url": "admin:cashbook_combined_main",
                "icon": "fas fa-university",
            },
            {
                "name": "카드사용내역입력",
                "url": "admin:card_upload",
                "icon": "fas fa-credit-card",
            },
            {
                "name": "예수금출납장",
                "url": "admin:deposit_ledger_main",
                "icon": "fas fa-hand-holding-usd",
            },
            {
                "name": "월간 예산집행 내역",
                "url": "admin:budget_execution_main",
                "icon": "fas fa-chart-pie",
            },
            {
                "name": "월간보고서(확정)",
                "url": "admin:confirmed_report",
                "icon": "fas fa-check-circle",
            },
            {
                "name": "계정과목등록(예산입력)",
                "url": "admin:account_main",
                "icon": "fas fa-cogs",
            },
        ],
    },
    "order_with_respect_to": [
        "finance",
        "finance.Budget",
        "finance.Transaction",
        "finance.CashBookCategory",
        "finance.Account",
        "finance.Member",
        "finance.FixedAsset",
        "finance.Settlement",
        "auth",
    ],
    "hide_models": ["finance.Account", "finance.CashBook"],
}

# Jazzmin UI 설정 - 사이드바 항상 펼침
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,  # 사이드바 자동 숨김 비활성화
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}
